[package]
name = "bankai-types"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
utoipa.workspace = true
alloy-primitives.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-beacon.workspace = true
alloy-consensus.workspace = true
cairo-air.workspace = true
stwo.workspace = true
starknet-crypto.workspace = true
tree_hash.workspace = true
tree_hash_derive.workspace = true