extern crate alloc;
use alloc::collections::BTreeMap;
use alloc::vec::Vec;
use core::slice;

use bankai_types::common::HashingFunction;
use bankai_types::inputs::ProofBundle;
use bankai_types::results::evm::op_stack::OpStackResults;
use bankai_types::results::evm::EvmResults;
use bankai_types::results::BatchResults;

use crate::bankai::stwo::verify_block_proof;
use crate::evm::beacon::BeaconVerifier;
use crate::evm::execution::ExecutionVerifier;
use crate::evm::op_stack::OpStackVerifier;
use crate::VerifyError;

/// Verifies a complete batch of proofs generated by the Bankai SDK
///
/// **All data returned by this function is cryptographically guaranteed to be valid.**
/// Once verification succeeds, no further validation is required. This guarantee is
/// provided by Bankai's stateless light client architecture using STWO zero-knowledge proofs.
///
/// This is the main entry point for verifying proof bundles. It performs a complete
/// verification of all proofs in the batch using a hierarchical approach:
///
/// 1. **STWO Proof Verification**: Verifies the zero-knowledge proof to establish trust
///    in the MMR roots for execution and beacon chains
/// 2. **Header Verification**: Verifies all execution and beacon headers using MMR inclusion
///    proofs against the trusted roots
/// 3. **Account Verification**: Verifies account proofs using Merkle Patricia Trie proofs
///    against verified execution headers
/// 4. **Transaction Verification**: Verifies transaction proofs using MPT proofs against
///    verified execution headers
///
/// # Arguments
///
/// * `wrapper` - A `ProofBundle` containing the STWO block proof and all individual proofs
///   to verify. This is typically generated by the `bankai-sdk` crate.
///
/// # Returns
///
/// Returns `BatchResults` containing all verified data:
/// - Verified execution headers with their block numbers and roots
/// - Verified beacon headers with their slot numbers
/// - Verified accounts with balances, nonces, and code hashes
/// - Verified transactions with their details
///
/// # Errors
///
/// Returns a `VerifyError` if any verification step fails:
/// - `InvalidStwoProof`: The STWO zero-knowledge proof is invalid
/// - `InvalidMmrProof`: An MMR inclusion proof failed
/// - `InvalidMmrRoot`: MMR root mismatch
/// - `InvalidHeaderHash`: Header hash doesn't match committed value
/// - `InvalidAccountProof`: Account MPT proof failed
/// - `InvalidTxProof`: Transaction MPT proof failed
/// - `InvalidStateRoot`: State root mismatch
/// - `InvalidExecutionHeaderProof`: Referenced header not found
///
/// # Example
///
/// ```no_run
/// use bankai_verify::verify_batch_proof;
/// use bankai_types::inputs::ProofBundle;
///
/// # fn example(proof_bundle: ProofBundle) -> Result<(), Box<dyn std::error::Error>> {
/// let results = verify_batch_proof(proof_bundle)?;
///
/// // Access verified execution headers
/// println!("Verified {} execution headers", results.evm.execution_header.len());
/// for header in &results.evm.execution_header {
///     println!("Block {}", header.number);
/// }
///
/// // Access verified accounts
/// println!("Verified {} accounts", results.evm.account.len());
/// for account in &results.evm.account {
///     println!("Balance: {}", account.balance);
/// }
///
/// // Access verified transactions
/// println!("Verified {} transactions", results.evm.tx.len());
/// # Ok(())
/// # }
/// ```
pub fn verify_batch_proof(wrapper: ProofBundle) -> Result<BatchResults, VerifyError> {
    let bankai_block = verify_block_proof(wrapper.block_proof, &wrapper.block)?;

    let exec_root = match wrapper.hashing_function {
        HashingFunction::Keccak => bankai_block.execution.mmr_root_keccak,
        HashingFunction::Poseidon => bankai_block.execution.mmr_root_poseidon,
    };
    let beacon_root = match wrapper.hashing_function {
        HashingFunction::Keccak => bankai_block.beacon.mmr_root_keccak,
        HashingFunction::Poseidon => bankai_block.beacon.mmr_root_poseidon,
    };

    let mut batch_results = BatchResults {
        evm: EvmResults {
            execution_header: Vec::new(),
            beacon_header: Vec::new(),
            account: Vec::new(),
            tx: Vec::new(),
            receipt: Vec::new(),
            storage_slot: Vec::new(),
        },
        op_stack: OpStackResults {
            header: Vec::new(),
            account: Vec::new(),
            tx: Vec::new(),
            receipt: Vec::new(),
            storage_slot: Vec::new(),
        },
    };

    if let Some(evm) = &wrapper.evm_proofs {
        if let Some(exec_headers) = &evm.execution_header_proof {
            for proof in exec_headers {
                let result = ExecutionVerifier::verify_header_proof(proof, exec_root)?;
                batch_results.evm.execution_header.push(result);
            }
        }

        if let Some(beacon_headers) = &evm.beacon_header_proof {
            for proof in beacon_headers {
                let result = BeaconVerifier::verify_header_proof(proof, beacon_root)?;
                batch_results.evm.beacon_header.push(result);
            }
        }

        if let Some(accounts) = &evm.account_proof {
            for account in accounts {
                let result = ExecutionVerifier::verify_account_proof(
                    account,
                    &batch_results.evm.execution_header,
                )?;
                batch_results.evm.account.push(result);
            }
        }

        if let Some(storage_slots) = &evm.storage_slot_proof {
            for proof in storage_slots {
                let result = ExecutionVerifier::verify_storage_slot_proof(
                    proof,
                    &batch_results.evm.execution_header,
                )?;
                batch_results.evm.storage_slot.push(result);
            }
        }

        if let Some(tx_proofs) = &evm.tx_proof {
            for proof in tx_proofs {
                let result =
                    ExecutionVerifier::verify_tx_proof(proof, &batch_results.evm.execution_header)?;
                batch_results.evm.tx.push(result);
            }
        }

        if let Some(receipt_proofs) = &evm.receipt_proof {
            for proof in receipt_proofs {
                let result = ExecutionVerifier::verify_receipt_proof(
                    proof,
                    &batch_results.evm.execution_header,
                )?;
                batch_results.evm.receipt.push(result);
            }
        }
    }

    if let Some(op_stack) = &wrapper.op_stack_proofs {
        let mut verified_op_headers = BTreeMap::new();

        if let Some(header_proofs) = &op_stack.header_proof {
            for proof in header_proofs {
                let header = OpStackVerifier::verify_header_proof(
                    proof,
                    bankai_block.op_chains.root,
                    wrapper.hashing_function,
                )?;
                verified_op_headers
                    .insert((proof.snapshot.chain_id, header.number), header.clone());
                batch_results.op_stack.header.push(header);
            }
        }

        if let Some(account_proofs) = &op_stack.account_proof {
            for proof in account_proofs {
                let header =
                    select_op_header(&verified_op_headers, proof.network_id, proof.block_number)?;
                let result =
                    ExecutionVerifier::verify_account_proof(proof, slice::from_ref(header))?;
                batch_results.op_stack.account.push(result);
            }
        }

        if let Some(storage_slot_proofs) = &op_stack.storage_slot_proof {
            for proof in storage_slot_proofs {
                let header =
                    select_op_header(&verified_op_headers, proof.network_id, proof.block_number)?;
                let result =
                    ExecutionVerifier::verify_storage_slot_proof(proof, slice::from_ref(header))?;
                batch_results.op_stack.storage_slot.push(result);
            }
        }

        if let Some(tx_proofs) = &op_stack.tx_proof {
            for proof in tx_proofs {
                let header =
                    select_op_header(&verified_op_headers, proof.network_id, proof.block_number)?;
                let result = ExecutionVerifier::verify_tx_proof(proof, slice::from_ref(header))?;
                batch_results.op_stack.tx.push(result);
            }
        }

        if let Some(receipt_proofs) = &op_stack.receipt_proof {
            for proof in receipt_proofs {
                let header =
                    select_op_header(&verified_op_headers, proof.network_id, proof.block_number)?;
                let result =
                    ExecutionVerifier::verify_receipt_proof(proof, slice::from_ref(header))?;
                batch_results.op_stack.receipt.push(result);
            }
        }
    }

    Ok(batch_results)
}

fn select_op_header(
    headers: &BTreeMap<(u64, u64), bankai_types::results::evm::execution::ExecutionHeader>,
    network_id: u64,
    block_number: u64,
) -> Result<&bankai_types::results::evm::execution::ExecutionHeader, VerifyError> {
    headers
        .get(&(network_id, block_number))
        .ok_or(VerifyError::InvalidExecutionHeaderProof)
}

#[cfg(test)]
mod tests {
    use super::select_op_header;
    use bankai_types::results::evm::execution::ExecutionHeader;
    use std::collections::BTreeMap;

    #[test]
    fn select_op_header_uses_network_id_and_block_number() {
        let mut headers = BTreeMap::new();
        headers.insert(
            (10, 7),
            ExecutionHeader {
                number: 7,
                beneficiary: alloy_primitives::Address::repeat_byte(0x10),
                ..Default::default()
            },
        );
        headers.insert(
            (8453, 7),
            ExecutionHeader {
                number: 7,
                beneficiary: alloy_primitives::Address::repeat_byte(0x20),
                ..Default::default()
            },
        );

        let header = select_op_header(&headers, 8453, 7).unwrap();

        assert_eq!(
            header.beneficiary,
            alloy_primitives::Address::repeat_byte(0x20)
        );
    }
}
